/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto.vista;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import proyecto.controlador.PacientController;
import proyecto.modelo.ListaSL;
import proyecto.modelo.Nodo;

/**
 *
 * @author Jou
 */
public class MovePacientPriority extends javax.swing.JDialog {

    private static ListaSL lsl;

    /**
     * Creates new form MovePacientPriority
     *
     * @param parent
     * @param modal
     */
    public MovePacientPriority(java.awt.Frame parent, boolean modal, ListaSL lsl) {
        super(parent, modal);
        MovePacientPriority.lsl = lsl;
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon icono = new ImageIcon("src/proyecto/iconos/Ambulancia.png");
        this.setIconImage(icono.getImage());
        addItemsJComboBox();
    }

    public static ListaSL getLsl() {
        return lsl;
    }

    public void setLsl(ListaSL lsl) {
        PacientForm.lsl = lsl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPrioPacientMove = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jBtnGuardar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mover pacientes por prioridad");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 101, 192));
        jLabel1.setText("<html>Mover pacientes<br>por prioridad</html>");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 16, -1, -1));

        jComboBoxPrioPacientMove.setModel(new javax.swing.DefaultComboBoxModel<>());
        jPanel1.add(jComboBoxPrioPacientMove, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Seleciona la prioridad de los pacientes a mover");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jBtnGuardar.setBackground(new java.awt.Color(56, 142, 60));
        jBtnGuardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnGuardar.setText("Guardar");
        jBtnGuardar.setPreferredSize(new java.awt.Dimension(95, 25));
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jBtnCancelar.setBackground(new java.awt.Color(211, 47, 47));
        jBtnCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.setPreferredSize(new java.awt.Dimension(95, 25));
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnCancelarActionPerformed
    {//GEN-HEADEREND:event_jBtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnGuardarActionPerformed
    {//GEN-HEADEREND:event_jBtnGuardarActionPerformed
        String et = (String) jComboBoxPrioPacientMove.getSelectedItem();
        if (PacientController.movePatientPriority(lsl, et)) {
            JOptionPane.showMessageDialog(this, "Se movieron los pacientes con prioridad (" + et + ") a otro hospital");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo cambiar los pacientes con prioridad (" + et + " a otro hospital");
        }
        this.dispose();
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void addItemsJComboBox() {
        Nodo nLista = lsl.getR();
        if (nLista != null) {
            while (nLista != null) {
                jComboBoxPrioPacientMove.addItem(nLista.getEtiqueta());
                nLista = nLista.getSiguiente();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovePacientPriority.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovePacientPriority.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovePacientPriority.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovePacientPriority.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(()
                -> {
            MovePacientPriority dialog = new MovePacientPriority(new javax.swing.JFrame(), true, lsl);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JComboBox<String> jComboBoxPrioPacientMove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
